### ISSUE TITLE
Relative URLs use incorrect folder

### ISSUE THREAD

**Issue by jandrieu** [satyrnjs/satyrn#38]
Using the files in the examples directory, I tried to use relative links to go between btcr.md and dids.md. They failed. I expect this is because the relative url is not using the directory of the loaded file.

Perhaps it is treating the code base directory as the CWD.

The files are currently in feature/btcr, but you can see this work with any two local files in the same folder (and not in the base folder for the app). A relative URL *should* be sufficient to link between the two, but it fails.

I tried with both "satyrn" and "_satyrn" targets. The latter opens a new Satyrn window. The former should open within the same window.

**Comment by wip-abramson** [comment]
I have looked into this. It also is because at least in part, when I coded the satyrn and _satyrn targets I was execting external urls. But actually these could be either external urls or file paths. We need some way to differentiate.

**Comment by jandrieu** [comment]
Yeah. 

I also realized we really have _two_ baseline contexts. One for the .html and one for the .md. The .html needs to point to our stylesheets, javascript, etc. which are easiest as relative URLs within the html.  But once rendered, we really are talking about relative to the .md, especially for links, but also for any images, etc.

I think the right answer is that before we convert the .md to html and inject it into the blank html template, we should adjust all of the relative urls in the HTML to point to their absolute path. THEN, set the base of the html page to the .md directory, by inserting a <base> tag in the <head> of the document.

I think this two step approach should do the trick--and I think we are guaranteed to have the information we need when we need it.

After that, relative URLs in the .md should work fine. So will local images or other assets, which is also good.

**Comment by jandrieu** [comment]
Add some file URLs to test.md to test that.

**Comment by wip-abramson** [comment]
I am going to close this and open a specific issue for fragments
